### ISSUE TITLE
Server fails to start, docker compose

### ISSUE THREAD

**Issue by jschneekloth** [atomicdata-dev/atomic-server#744]
Following [these](https://docs.atomicdata.dev/atomicserver/installation) instructions to setup via docker (docker compose in this example).

My docker compose:
```
---
services:
  atomic-server:
    image: joepmeneer/atomic-server
    container_name: atomic-server
    restart: unless-stopped
    ports:
      - 9883:80
    volumes:
      - ~/volumes/atomic-data/atomic-storage:/atomic-storage
```

When running `docker compose up -d` I see the following output in logs and the server doesn't startup:
```
atomic-server  | exec /atomic-server-bin: exec format error
atomic-server  | exec /atomic-server-bin: exec format error
atomic-server  | exec /atomic-server-bin: exec format error
atomic-server  | exec /atomic-server-bin: exec format error
atomic-server  | exec /atomic-server-bin: exec format error
atomic-server  | exec /atomic-server-bin: exec format error
atomic-server  | exec /atomic-server-bin: exec format error
```

Any ideas on what might be going on here?
