### ISSUE TITLE
CI builds not running in main / develop

### ISSUE THREAD

**Issue by joepio** [atomicdata-dev/atomic-server#948]
https://github.com/atomicdata-dev/atomic-server/actions/runs/10491551686/job/29060960775

**Comment by joepio** [comment]
Hoped this would work

```yml
      - name: Earthly +builds
        if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
        run: earthly --org ontola --ci --sat henk -P --push +builds --tags="${{ steps.meta.outputs.tags }}"
```

But it does not
